name: Awesome-CV

on: [push]

jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olivierodo/awesome-cv-action@0.0.1
      env:
        ROSHAN_TOKEN: ${{ secrets.ROSHAN_TOKEN }}
      with:
        FILE_NAME: 'resume.tex'